// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwPBYKtmnbCPWoVBFDuYGenXV5mJVAMEY',
    appId: '1:367691004974:web:61ac2950855271a4a773bf',
    messagingSenderId: '367691004974',
    projectId: 'finalyear2020-68aaf',
    authDomain: 'finalyear2020-68aaf.firebaseapp.com',
    databaseURL: 'https://finalyear2020-68aaf.firebaseio.com',
    storageBucket: 'finalyear2020-68aaf.appspot.com',
    measurementId: 'G-D3T34L6ERF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQP7rxurFmO_QbJZXG10gRnjYQkAu_-k4',
    appId: '1:367691004974:android:abd49fdfd727c579a773bf',
    messagingSenderId: '367691004974',
    projectId: 'finalyear2020-68aaf',
    databaseURL: 'https://finalyear2020-68aaf.firebaseio.com',
    storageBucket: 'finalyear2020-68aaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCKdmEN_xcyDu0oHtS36ohJjt5kqai9WQ',
    appId: '1:367691004974:ios:1c59f93e2f11599ba773bf',
    messagingSenderId: '367691004974',
    projectId: 'finalyear2020-68aaf',
    databaseURL: 'https://finalyear2020-68aaf.firebaseio.com',
    storageBucket: 'finalyear2020-68aaf.appspot.com',
    androidClientId: '367691004974-adov98dh71j3cu6f6at19cvhnvqsc79c.apps.googleusercontent.com',
    iosClientId: '367691004974-hceg8br2njsgp6vehdvo09ra331jej2c.apps.googleusercontent.com',
    iosBundleId: 'com.kurama.arbor',
  );
}
